sudo: false
language: java
install: true

jdk:
  - openjdk8

addons:
  hosts:
    - HBASE_HOST

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify -V -U -B

after_success:
  - bash <(echo "SUCCESS")

services:
  - docker

dist: trusty